In [1]:
from sklearn.preprocessing import KBinsDiscretizer, Binarizer
import numpy as np
x = np.array([10, 20, 30, 40, 50, 90]).reshape(-1, 1)
print(KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit_transform(x).ravel())
print(KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile').fit_transform(x).ravel())
print(Binarizer(threshold=35).fit_transform(x).ravel())

[0. 0. 0. 1. 1. 2.]
[0. 0. 1. 1. 2. 2.]
[0 0 0 1 1 1]


C:\Users\s3624\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
